### ISSUE TITLE
数据库文件没有

### ISSUE THREAD

**Issue by ghost** [a6678696/JXC#2]
能不能提供下数据库文件呀

**Comment by a6678696** [comment]
文件已上传

**Comment by ghost** [comment]
密码怎么没有加密？太不安全了这样

**Comment by a6678696** [comment]
加密很简单的,没弄

**Comment by ghost** [comment]
好吧，系统弄得倒是挺好的，整好需要跟这个一样的来着

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/26890443/101484289-5d686d80-3994-11eb-9f07-abcaad60b508.png)
这个要咋整，报这个错误！

**Comment by a6678696** [comment]
你是新手还是老手?

**Comment by ghost** [comment]
我还新手不怎么会！不过这个项目所有的功能我整合需要，所以想来看看

**Comment by a6678696** [comment]
包没有导入

**Comment by a6678696** [comment]
电脑安装maven了没有?

**Comment by ghost** [comment]
maven我安装了，其他依赖也正常，不过pom文件也没报错，只是springboot版本号是红色的

**Comment by ghost** [comment]
你tomcat用的是多少？我这是1.8的。不知道使是不是版本不匹配了！

**Comment by a6678696** [comment]
你去百度一下,我换了新电脑后也是直接可以运行的

**Comment by a6678696** [comment]
我用的也是1.8

**Comment by a6678696** [comment]
jdk1.8

**Comment by a6678696** [comment]
你说的1.8是jdk吧,tomcat应该没有1.8

**Comment by ghost** [comment]
对对，说错了，是jdk

**Comment by ghost** [comment]
好吧，谢谢您，有机会加QQ好友，沟通沟通

**Comment by a6678696** [comment]
嗯

**Comment by ghost** [comment]
我File”----&gt;“Invalidate Caches / Restart”下然后就好了，现在没发现爆红，运行看下，谢谢啊
